### ISSUE TITLE
cuFFT always fail to allocate GPU or CPU memory

### ISSUE THREAD

**Issue by JiangXL** [computational-imaging/ThreeDeconv.jl#2]
When I run `ThreeDeconv.deconvolve`  in the first time, it work well.
But at second time, error occur:
`CUFFTError(code 2, cuFFT failed to allocate GPU or CPU memory)
`
Then I run same command against, no error!!!  I am confused why GC.gc() don't release GPU memory. 

I run Julia 1.2 in Fedora 30 with a NVIDIA 2080Ti.

What should I do?

**Comment by hayatoikoma** [comment]
Sorry, I just recognized this issue.

Yes, I remember I encountered this issue. Have you resolved it? I think this is what you can consult with [CuArrays.jl](https://github.com/JuliaGPU/CuArrays.jl).

**Comment by hayatoikoma** [comment]
I have updated the package to use [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl) with Julia v1.5. So, there is some chance where you don't experience the error anymore. FYI.

**Comment by JiangXL** [comment]
Thanks! No more this error now.
