### ISSUE TITLE
Please update so this works on current Julia 1.7

### ISSUE THREAD

**Issue by GeorgeMcNamara** [computational-imaging/ThreeDeconv.jl#7]
Please update so this works on current Julia 1.6. Failure:

Hit the key ] in the Julia REPL to ender the Pkg REPL-mode, and run
pkg> add https://github.com/computational-imaging/ThreeDeconv.jl.git

resulted in error ... for package [CUDA]
Screen shot attached.

![ThreeDeconv failed with CUDA error in Julia 1p6](https://user-images.githubusercontent.com/82233094/114220207-b1cb2c00-9939-11eb-9ccd-6b2d6c67a294.png)

**Comment by hayatoikoma** [comment]
Updated.
